export const MONO = { fontFamily: "'JetBrains Mono', 'SF Mono', monospace" };
export const SANS = { fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif" };
export const DISP = { fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif" };
export const CY   = '#00d395';   // primary green — gains, active states
export const ICE  = '#60a5fa';   // AI/machine blue — PM outputs
export const GREEN = '#00d395';
export const RED   = '#ff4d4d';
export const BG    = '#0a0e1a';
export const SURF  = '#111827';
