export const FONT = { fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif" };
export const MONO = { fontFamily: "ui-monospace, 'SF Mono', 'Fira Code', monospace" };
export const DISP = { fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif" };
export const SANS = { fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif" };
export const CY   = '#38e0d4';
export const ICE  = '#3B82F6';
export const GRN  = '#00C805';
export const RED  = '#FF3B30';
export const GOLD = '#F59E0B';
