export const FONT = { fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif" };
export const MONO = { fontFamily: "ui-monospace, 'SF Mono', 'Fira Code', monospace" };
export const DISP = { fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif" };
export const SANS = { fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif" };
export const CY   = '#3B82F6';
export const ICE  = '#3B82F6';
export const GRN  = '#22C55E';
export const RED  = '#EF4444';
export const GOLD = '#F59E0B';
